# Generated by Django 3.0.4 on 2020-04-19 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airlines_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='airport',
            name='country',
        ),
        migrations.AlterField(
            model_name='passenger',
            name='checked_in',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
