# Generated by Django 3.0.4 on 2020-04-14 19:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('airlines_app', '0002_auto_20200414_1836'),
    ]

    operations = [
        migrations.AddField(
            model_name='passenger',
            name='flight',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='airlines_app.Flight'),
            preserve_default=False,
        ),
    ]
