# Generated by Django 3.0.4 on 2020-04-19 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airlines_app', '0002_auto_20200419_0742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passenger',
            name='nationality',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
