# Generated by Django 3.0.4 on 2020-04-15 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('airlines_app', '0003_passenger_flight'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkedinluggage',
            name='number',
        ),
    ]
