# Generated by Django 3.0.4 on 2020-04-15 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airlines_app', '0004_remove_checkedinluggage_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkedinluggage',
            name='luggage_type',
            field=models.CharField(max_length=64),
        ),
    ]
