# Generated by Django 3.0.4 on 2020-04-17 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airlines_app', '0007_auto_20200415_2257'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='paid',
            field=models.BooleanField(default=False),
        ),
    ]
