# Generated by Django 3.0.4 on 2020-04-17 20:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('airlines_app', '0008_booking_paid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_number', models.CharField(max_length=16)),
                ('expiration_date', models.CharField(max_length=5)),
                ('card_holder_name', models.CharField(max_length=64)),
                ('cvv', models.CharField(max_length=3)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='airlines_app.Booking')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
