# Generated by Django 3.0.4 on 2020-04-18 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airlines_app', '0009_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='passenger',
            name='checked_in',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='passenger',
            name='passport',
            field=models.CharField(max_length=64, null=True, unique=True),
        ),
    ]
