# Generated by Django 3.0.4 on 2020-04-18 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airlines_app', '0010_auto_20200418_0936'),
    ]

    operations = [
        migrations.AddField(
            model_name='passenger',
            name='age_range',
            field=models.CharField(max_length=16, null=True),
        ),
    ]
